import type { ScanSummary, Finding, Severity } from "../core/types.js";

const SEVERITY_BADGES: Record<Severity, string> = {
  critical: "[CRIT]",
  high: "[HIGH]",
  medium: "[MED ]",
  low: "[LOW ]",
};

function severitySort(s: Severity): number {
  return { critical: 0, high: 1, medium: 2, low: 3 }[s];
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

export function markdownReporter(summary: ScanSummary, findings: Finding[]): string {
  const lines: string[] = [];

  lines.push("# VibeGuard Security Scan Report");
  lines.push("");
  lines.push("## Scan Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| **Target** | ${summary.target} |`);
  lines.push(`| **Profile** | ${summary.profile} |`);
  lines.push(`| **Framework** | ${summary.framework ?? "Unknown"} |`);
  lines.push(`| **Score** | ${summary.score}/100 |`);
  lines.push(`| **Total Findings** | ${summary.totalFindings} |`);
  lines.push(`| **Duration** | ${formatDuration(summary.scanDuration)} |`);
  lines.push(`| **Scan Date** | ${new Date(summary.scanDate).toUTCString()} |`);
  lines.push("");

  lines.push("### Severity Breakdown");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const s of ["critical", "high", "medium", "low"] as Severity[]) {
    if ((summary.bySeverity[s] ?? 0) > 0) {
      lines.push(`| ${SEVERITY_BADGES[s]} ${s.charAt(0).toUpperCase() + s.slice(1)} | ${summary.bySeverity[s]} |`);
    }
  }
  lines.push("");

  if (summary.launchBlockers.length > 0) {
    lines.push("## Launch Blockers");
    lines.push("");
    lines.push("<details>");
    lines.push("<summary>Click to expand (${summary.launchBlockers.length} blockers)</summary>");
    lines.push("");
    for (const blocker of summary.launchBlockers) {
      lines.push(`### ${blocker.title}`);
      lines.push("");
      lines.push(`- **Severity:** ${SEVERITY_BADGES[blocker.severity]} ${blocker.severity}`);
      lines.push(`- **Category:** ${blocker.category}`);
      lines.push(`- **Rule:** ${blocker.ruleId}`);
      if (blocker.location?.file) lines.push(`- **File:** ${blocker.location.file}:${blocker.location.line ?? ""}`);
      if (blocker.location?.url) lines.push(`- **URL:** ${blocker.location.url}`);
      lines.push("");
      lines.push(blocker.description);
      lines.push("");
      if (blocker.evidence.length > 0) {
        lines.push("**Evidence:**");
        lines.push("");
        for (const ev of blocker.evidence) {
          lines.push("  - " + ev);
        }
        lines.push("");
      }
    }
    lines.push("</details>");
    lines.push("");
  }

  lines.push("## Findings by Category");
  lines.push("");

  const grouped = new Map<string, Finding[]>();
  for (const f of findings) {
    if (!grouped.has(f.category)) grouped.set(f.category, []);
    grouped.get(f.category)!.push(f);
  }

  const sortedCategories = [...grouped.entries()].sort((a, b) => {
    const maxA = Math.min(...a[1].map((f) => severitySort(f.severity)));
    const maxB = Math.min(...b[1].map((f) => severitySort(f.severity)));
    return maxA - maxB;
  });

  for (const [category, cats] of sortedCategories) {
    lines.push(`### ${category.charAt(0).toUpperCase() + category.slice(1)}`);
    lines.push("");
    lines.push("| Severity | Title | Location |");
    lines.push("|----------|-------|----------|");
    const sorted = [...cats].sort((a, b) => severitySort(a.severity) - severitySort(b.severity));
    for (const f of sorted) {
      const loc = f.location?.file
        ? `${f.location.file}${f.location.line ? `:${f.location.line}` : ""}`
        : f.location?.url ?? "-";
      lines.push(`| ${SEVERITY_BADGES[f.severity]} | ${f.title} | ${loc} |`);
    }
    lines.push("");
  }

  const owaspCategories = new Set<string>();
  for (const f of findings) {
    if (f.owaspTop10) f.owaspTop10.forEach((o) => owaspCategories.add(o));
  }
  if (owaspCategories.size > 0) {
    lines.push("## OWASP Top 10 Coverage");
    lines.push("");
    lines.push("| Category | Findings |");
    lines.push("|----------|----------|");
    for (const ow of [...owaspCategories].sort()) {
      const count = findings.filter((f) => f.owaspTop10?.includes(ow)).length;
      lines.push(`| ${ow} | ${count} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "Report generated by [VibeGuard](https://github.com/anomalyco/vibe-guard). "
    + "This is a security assessment tool and may produce false positives. "
    + "Review each finding before taking action.",
  );

  return lines.join("\n");
}
